name: built_value_examples
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: rafal.wachol <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_value: ^6.1.4
  built_collection: ^4.0.0
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build: ^1.0.1
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
